version: '3.5'

services:
  nano:
    container_name: bot
    build: .
    command: python nano/client.py
    volumes:
      - ./nano:/app/nano
    ports:
      - "8000:8000"
    environment:
      RUNNING_DOCKER_COMPOSE: 1
      DISCORD_BOT_TOKEN: /var/run/secrets/discord_bot_token
      COINAPI_KEY: /var/run/secrets/coinapi_key
      OPENWEATHERMAP_KEY: /var/run/secrets/openweathermap_key
    secrets:
      - discord_bot_token
      - coinapi_key
      - openweathermap_key

secrets:
  discord_bot_token:
    file: ./secrets/discord_bot_token
  coinapi_key:
    file: ./secrets/coinapi_key
  openweathermap_key:
    file: ./secrets/openweathermap_key
