version: '3.5'

services:
  hakase:
    container_name: bot
    build: .
    command: python hakase/client.py
    ports:
      - "8000:8000"
    environment:
      RUNNING_DOCKER_COMPOSE: 1
      DISCORD_BOT_TOKEN: /var/run/secrets/discord_bot_token
    secrets:
      - discord_bot_token

secrets:
  discord_bot_token:
    file: ./secrets/discord_bot_token
